package realEstateService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-14T13:58:33.997+02:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "RealEstateAgency",
                  wsdlLocation = "http://localhost:8080/RealEstateAgency/RealEstateAgency?wsdl",
                  targetNamespace = "http://www.example.org/RealEstateAgency/")
public class RealEstateAgency_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/RealEstateAgency/", "RealEstateAgency");
    public final static QName RealEstateAgencyImplPort = new QName("http://www.example.org/RealEstateAgency/", "RealEstateAgencyImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RealEstateAgency/RealEstateAgency?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RealEstateAgency_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/RealEstateAgency/RealEstateAgency?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RealEstateAgency_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RealEstateAgency_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RealEstateAgency_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RealEstateAgency_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RealEstateAgency_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RealEstateAgency_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RealEstateAgency
     */
    @WebEndpoint(name = "RealEstateAgencyImplPort")
    public RealEstateAgency getRealEstateAgencyImplPort() {
        return super.getPort(RealEstateAgencyImplPort, RealEstateAgency.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RealEstateAgency
     */
    @WebEndpoint(name = "RealEstateAgencyImplPort")
    public RealEstateAgency getRealEstateAgencyImplPort(WebServiceFeature... features) {
        return super.getPort(RealEstateAgencyImplPort, RealEstateAgency.class, features);
    }

}
