package realEstateService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-14T13:58:33.953+02:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://www.example.org/RealEstateAgency/", name = "RealEstateAgency")
@XmlSeeAlso({ObjectFactory.class})
public interface RealEstateAgency {

    @WebMethod
    @RequestWrapper(localName = "getUserByID", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetUserByID")
    @ResponseWrapper(localName = "getUserByIDResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetUserByIDResponse")
    @WebResult(name = "out", targetNamespace = "")
    public realEstateService.UserType getUserByID(
        @WebParam(name = "userID", targetNamespace = "")
        int userID
    );

    @WebMethod
    @RequestWrapper(localName = "getAllRealEstates", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetAllRealEstates")
    @ResponseWrapper(localName = "getAllRealEstatesResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetAllRealEstatesResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<realEstateService.RealEstateType> getAllRealEstates(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod
    @RequestWrapper(localName = "buyRealEstate", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.BuyRealEstate")
    @ResponseWrapper(localName = "buyRealEstateResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.BuyRealEstateResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean buyRealEstate(
        @WebParam(name = "buyerID", targetNamespace = "")
        int buyerID,
        @WebParam(name = "realEstateID", targetNamespace = "")
        int realEstateID
    );

    @WebMethod
    @RequestWrapper(localName = "deleteComment", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.DeleteComment")
    @ResponseWrapper(localName = "deleteCommentResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.DeleteCommentResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean deleteComment(
        @WebParam(name = "commentID", targetNamespace = "")
        int commentID
    );

    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.AddUserResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addUser(
        @WebParam(name = "in", targetNamespace = "")
        realEstateService.UserType in
    );

    @WebMethod(action = "http://www.example.org/RealEstateAgency/getUser")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetUserResponse")
    @WebResult(name = "out", targetNamespace = "")
    public realEstateService.UserType getUser(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username
    );

    @WebMethod
    @RequestWrapper(localName = "addRealEstate", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.AddRealEstate")
    @ResponseWrapper(localName = "addRealEstateResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.AddRealEstateResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addRealEstate(
        @WebParam(name = "in", targetNamespace = "")
        realEstateService.RealEstateType in
    );

    @WebMethod
    @RequestWrapper(localName = "getRealEstatesSold", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetRealEstatesSold")
    @ResponseWrapper(localName = "getRealEstatesSoldResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetRealEstatesSoldResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<realEstateService.RealEstateType> getRealEstatesSold(
        @WebParam(name = "userID", targetNamespace = "")
        int userID
    );

    @WebMethod
    @RequestWrapper(localName = "searchRealEstateByCity", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.SearchRealEstateByCity")
    @ResponseWrapper(localName = "searchRealEstateByCityResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.SearchRealEstateByCityResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<realEstateService.RealEstateType> searchRealEstateByCity(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod
    @RequestWrapper(localName = "getCommentsOn", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetCommentsOn")
    @ResponseWrapper(localName = "getCommentsOnResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetCommentsOnResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<realEstateService.CommentType> getCommentsOn(
        @WebParam(name = "userID", targetNamespace = "")
        int userID
    );

    @WebMethod
    @RequestWrapper(localName = "validateUser", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.ValidateUser")
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.ValidateUserResponse")
    @WebResult(name = "out", targetNamespace = "")
    public realEstateService.UserType validateUser(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod
    @RequestWrapper(localName = "getCommentsFrom", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetCommentsFrom")
    @ResponseWrapper(localName = "getCommentsFromResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetCommentsFromResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<realEstateService.CommentType> getCommentsFrom(
        @WebParam(name = "userID", targetNamespace = "")
        int userID
    );

    @WebMethod
    @RequestWrapper(localName = "searchRealEstateByName", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.SearchRealEstateByName")
    @ResponseWrapper(localName = "searchRealEstateByNameResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.SearchRealEstateByNameResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<realEstateService.RealEstateType> searchRealEstateByName(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod
    @RequestWrapper(localName = "getRealEstatesBought", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetRealEstatesBought")
    @ResponseWrapper(localName = "getRealEstatesBoughtResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.GetRealEstatesBoughtResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<realEstateService.RealEstateType> getRealEstatesBought(
        @WebParam(name = "userID", targetNamespace = "")
        int userID
    );

    @WebMethod
    @RequestWrapper(localName = "deleteRealEstate", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.DeleteRealEstate")
    @ResponseWrapper(localName = "deleteRealEstateResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.DeleteRealEstateResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean deleteRealEstate(
        @WebParam(name = "realEstateID", targetNamespace = "")
        int realEstateID
    );

    @WebMethod
    @RequestWrapper(localName = "addComment", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.AddComment")
    @ResponseWrapper(localName = "addCommentResponse", targetNamespace = "http://www.example.org/RealEstateAgency/", className = "realEstateService.AddCommentResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addComment(
        @WebParam(name = "in", targetNamespace = "")
        realEstateService.CommentType in
    );
}
