
package bankService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-12T12:12:29.218+02:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "addCreditFault", targetNamespace = "http://www.example.org/Bank/")
public class AddCreditFault_Exception extends Exception {

    private bankService.AddCreditFault addCreditFault;

    public AddCreditFault_Exception() {
        super();
    }

    public AddCreditFault_Exception(String message) {
        super(message);
    }

    public AddCreditFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AddCreditFault_Exception(String message, bankService.AddCreditFault addCreditFault) {
        super(message);
        this.addCreditFault = addCreditFault;
    }

    public AddCreditFault_Exception(String message, bankService.AddCreditFault addCreditFault, java.lang.Throwable cause) {
        super(message, cause);
        this.addCreditFault = addCreditFault;
    }

    public bankService.AddCreditFault getFaultInfo() {
        return this.addCreditFault;
    }
}
