package bankService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-12T12:12:29.251+02:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://www.example.org/Bank/", name = "Bank")
@XmlSeeAlso({ObjectFactory.class})
public interface Bank {

    @WebMethod
    @RequestWrapper(localName = "getCredits", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetCredits")
    @ResponseWrapper(localName = "getCreditsResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetCreditsResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<bankService.CreditType> getCredits(
        @WebParam(name = "accountID", targetNamespace = "")
        int accountID
    );

    @WebMethod
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetAccountsResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<bankService.AccountType> getAccounts(
        @WebParam(name = "userID", targetNamespace = "")
        int userID
    );

    @WebMethod
    @RequestWrapper(localName = "addAccount", targetNamespace = "http://www.example.org/Bank/", className = "bankService.AddAccount")
    @ResponseWrapper(localName = "addAccountResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.AddAccountResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addAccount(
        @WebParam(name = "userID", targetNamespace = "")
        int userID
    );

    @WebMethod
    @RequestWrapper(localName = "transferMoney", targetNamespace = "http://www.example.org/Bank/", className = "bankService.TransferMoney")
    @ResponseWrapper(localName = "transferMoneyResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.TransferMoneyResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean transferMoney(
        @WebParam(name = "in", targetNamespace = "")
        bankService.TransactionType in
    );

    @WebMethod
    @RequestWrapper(localName = "getTransactionsFrom", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetTransactionsFrom")
    @ResponseWrapper(localName = "getTransactionsFromResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetTransactionsFromResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<bankService.TransactionType> getTransactionsFrom(
        @WebParam(name = "accountID", targetNamespace = "")
        int accountID
    );

    @WebMethod
    @RequestWrapper(localName = "getTransactionsTo", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetTransactionsTo")
    @ResponseWrapper(localName = "getTransactionsToResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetTransactionsToResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.util.List<bankService.TransactionType> getTransactionsTo(
        @WebParam(name = "accountID", targetNamespace = "")
        int accountID
    );

    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://www.example.org/Bank/", className = "bankService.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.AddUserResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addUser(
        @WebParam(name = "in", targetNamespace = "")
        bankService.BankUserType in
    );

    @WebMethod(action = "http://www.example.org/Bank/getUser")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.GetUserResponse")
    @WebResult(name = "out", targetNamespace = "")
    public bankService.BankUserType getUser(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username
    );

    @WebMethod
    @RequestWrapper(localName = "evaluateCreditCapability", targetNamespace = "http://www.example.org/Bank/", className = "bankService.EvaluateCreditCapability")
    @ResponseWrapper(localName = "evaluateCreditCapabilityResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.EvaluateCreditCapabilityResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean evaluateCreditCapability(
        @WebParam(name = "accountID", targetNamespace = "")
        int accountID
    );

    @WebMethod
    @RequestWrapper(localName = "addCredit", targetNamespace = "http://www.example.org/Bank/", className = "bankService.AddCredit")
    @ResponseWrapper(localName = "addCreditResponse", targetNamespace = "http://www.example.org/Bank/", className = "bankService.AddCreditResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addCredit(
        @WebParam(name = "accountID", targetNamespace = "")
        int accountID,
        @WebParam(name = "amount", targetNamespace = "")
        double amount
    ) throws AddCreditFault_Exception;
}
