package bankService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-14T12:57:17.825+02:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "Bank",
                  wsdlLocation = "http://localhost:8080/Bank/Bank?wsdl",
                  targetNamespace = "http://www.example.org/Bank/")
public class Bank_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/Bank/", "Bank");
    public final static QName BankImplPort = new QName("http://www.example.org/Bank/", "BankImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Bank/Bank?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Bank_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Bank/Bank?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Bank_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Bank_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Bank_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Bank_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Bank_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Bank_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Bank
     */
    @WebEndpoint(name = "BankImplPort")
    public Bank getBankImplPort() {
        return super.getPort(BankImplPort, Bank.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Bank
     */
    @WebEndpoint(name = "BankImplPort")
    public Bank getBankImplPort(WebServiceFeature... features) {
        return super.getPort(BankImplPort, Bank.class, features);
    }

}
